# -*- coding: utf-8 -*-
"""317-7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jXtWY6vlcNvBLBSIqNhs2YkeQe4n0sj-

**La fórmula es**

X = 4 - 4/3 + 4/5 - 4/7 + 4/9 - ....

Inicializar k = 1 // esta variable se usará como denominador de la fórmula de leibniz, se incrementará en 2
Initialize sum = 0 // sum agregará todos los elementos de la serie
Ejecutar un bucle for de 0 a 1000000 // en este valor, obtenemos el valor más preciso de Pi
Dentro del bucle for, verifique si i% 2 == 0 y luego sum = sum + 4 / k
De lo contrario, haz sum = sum-4 / k
Incrementar k en 2, ir al paso 3
"""

k = 1  
s = 0  
for i in range(1000000):     
    if i % 2 == 0:
      s  =s+ (4/k )
    else:         
        s=s-  (4/k)
    k += 2      
print(s)